server:
  port: 8085

spring:
  application:
    name: notification-service
  datasource:
    url: jdbc:postgresql://localhost:5432/notification_db
    username: postgres
    password: 1234
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  mail:
    host: ${SPRING_MAIL_HOST:mock}
    port: ${SPRING_MAIL_PORT:587}
    username: ${SPRING_MAIL_USERNAME:mock}
    password: ${SPRING_MAIL_PASSWORD:mock}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
