server:
  port: 8085

spring:
  application:
    name: notification-service
  datasource:
    url: jdbc:postgresql://localhost:5432/notification_db
    username: postgres
    password: 1234
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

brevo:
  api-key: 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
  sender-name: LMS Platform
  sender-email: dinithplatform@gmail.com
